

#ifndef _NICKSVCHAT_CHAT_CONFIG
#define _NICKSVCHAT_CHAT_CONFIG

#define NICKSVCHAT_VERSION_MAJOR 0
#define NICKSVCHAT_VERSION_MINOR 1
#define NICKSVCHAT_VERSION_PATCH 0



#endif //_NICKSVCHAT_CHAT_CONFIG
