#ifndef _NICKSVCHAT_CHAT_CONFIG
#define _NICKSVCHAT_CHAT_CONFIG
#pragma once

#define NICKSVCHAT_VERSION_MAJOR 0
#define NICKSVCHAT_VERSION_MINOR 1
#define NICKSVCHAT_VERSION_PATCH 0

#define BUILD_SHARED_LIBS

#ifndef BUILD_SHARED_LIBS
    #define NICKSVCHAT_STATIC_LINK
#endif

#endif //_NICKSVCHAT_CHAT_CONFIG
